version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  chat-local:
    environment:
      - CONFIG_PATH=local.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "50053:50053"
        - "8080:8080"
        - "8090:8090"
    depends_on:
      - pg-local

  chat-prod:
    image: "${REGISTRY}/${CHAT_IMAGE_NAME}:${TAG_NAME}"
    environment:
      - CONFIG_PATH=prod.env
    ports:
      - "50054:50054"
    depends_on:
      - pg-prod

  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - local.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  pg-prod:
    image: postgres:14-alpine3.17
    env_file:
      - prod.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  migrator-local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local
    depends_on:
      - pg-local

  migrator-prod:
    image: "${REGISTRY}/${MIGRATOR_IMAGE_NAME}:${TAG_NAME}"
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-prod
    depends_on:
      - pg-prod
