version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:
  grafana_data:

services:
  chat-local:
    environment:
      - CONFIG_PATH=local.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "50053:50053"
        - "2112:2112"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - pg-local

  chat-prod:
    image: "${REGISTRY}/${CHAT_IMAGE_NAME}:${TAG_NAME}"
    environment:
      - CONFIG_PATH=prod.env
    ports:
      - "50054:50054"
    depends_on:
      - pg-prod

  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - local.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  pg-prod:
    image: postgres:14-alpine3.17
    env_file:
      - prod.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  migrator-local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local
    depends_on:
      - pg-local

  migrator-prod:
    image: "${REGISTRY}/${MIGRATOR_IMAGE_NAME}:${TAG_NAME}"
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-prod
    depends_on:
      - pg-prod

  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./alerts.yaml:/etc/prometheus/alerts.yml

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
